"use client";

import { useLocale } from "next-intl";
import { useNavItems } from "@/hooks/useNavItems";
import { Link } from "@/i18n/navigation";
import { PageLayout } from "@/components/ui";

const CONTENT = {
  zh: {
    title: "服务条款",
    lastUpdated: "最后更新：2025年4月1日",
    sections: [
      {
        heading: "1. 服务描述",
        body: "51yijing.com 是一个基于人工智能的易经在线占卜平台，提供传统三币摇卦和 AI 智能解读服务。本服务仅供文化学习和娱乐参考之用。",
      },
      {
        heading: "2. 免责声明",
        body: "本站所有占卜结果和 AI 解读内容均由人工智能生成，仅供娱乐和个人反思参考。这些内容不构成医疗、金融、法律或任何其他专业建议。\n\n对于因使用本站占卜结果而做出的任何决定，我们不承担任何责任。如需专业建议，请咨询相关领域的合格专业人士。",
      },
      {
        heading: "3. 用户行为规范",
        body: "使用本服务时，您同意：\n• 不滥用或恶意使用本服务\n• 不尝试破坏、干扰或未经授权访问本站系统\n• 不将本服务用于任何非法目的\n• 不冒充他人或虚假陈述您与任何个人或实体的关系",
      },
      {
        heading: "4. 知识产权",
        body: "本站的设计、代码、AI 算法、内容和品牌标识均受知识产权法保护。未经书面许可，不得复制、修改、分发或以其他方式使用本站的任何内容。\n\n易经原文属于公共领域文化遗产，AI 生成的解读内容版权归本站所有。",
      },
      {
        heading: "5. 服务变更",
        body: "我们保留随时修改、暂停或终止服务的权利，恕不另行通知。我们也可能不时更新这些条款。继续使用本服务即表示您接受更新后的条款。",
      },
      {
        heading: "6. 适用法律",
        body: "本条款受中华人民共和国法律管辖。任何因本条款引起的争议应通过友好协商解决；协商不成的，提交有管辖权的人民法院裁决。",
      },
    ],
  },
  "zh-TW": {
    title: "服務條款",
    lastUpdated: "最後更新：2025年4月1日",
    sections: [
      {
        heading: "1. 服務描述",
        body: "51yijing.com 是一個基於人工智慧的易經線上占卜平台，提供傳統三幣搖卦和 AI 智慧解讀服務。本服務僅供文化學習和娛樂參考之用。",
      },
      {
        heading: "2. 免責聲明",
        body: "本站所有占卜結果和 AI 解讀內容均由人工智慧生成，僅供娛樂和個人反思參考。這些內容不構成醫療、金融、法律或任何其他專業建議。\n\n對於因使用本站占卜結果而做出的任何決定，我們不承擔任何責任。如需專業建議，請諮詢相關領域的合格專業人士。",
      },
      {
        heading: "3. 使用者行為規範",
        body: "使用本服務時，您同意：\n• 不濫用或惡意使用本服務\n• 不嘗試破壞、干擾或未經授權存取本站系統\n• 不將本服務用於任何非法目的\n• 不冒充他人或虛假陳述您與任何個人或實體的關係",
      },
      {
        heading: "4. 智慧財產權",
        body: "本站的設計、程式碼、AI 演算法、內容和品牌標識均受智慧財產權法保護。未經書面許可，不得複製、修改、散佈或以其他方式使用本站的任何內容。\n\n易經原文屬於公共領域文化遺產，AI 生成的解讀內容版權歸本站所有。",
      },
      {
        heading: "5. 服務變更",
        body: "我們保留隨時修改、暫停或終止服務的權利，恕不另行通知。我們也可能不時更新這些條款。繼續使用本服務即表示您接受更新後的條款。",
      },
      {
        heading: "6. 適用法律",
        body: "本條款受中華人民共和國法律管轄。任何因本條款引起的爭議應透過友好協商解決；協商不成的，提交有管轄權的人民法院裁決。",
      },
    ],
  },
  en: {
    title: "Terms of Service",
    lastUpdated: "Last updated: April 1, 2025",
    sections: [
      {
        heading: "1. Service Description",
        body: "51yijing.com is an AI-powered I Ching online divination platform offering traditional three-coin divination and AI-powered interpretation services. This service is intended for cultural learning and entertainment purposes only.",
      },
      {
        heading: "2. Disclaimer",
        body: "All divination results and AI interpretations on this site are generated by artificial intelligence and are provided solely for entertainment and personal reflection. They do not constitute medical, financial, legal, or any other professional advice.\n\nWe assume no liability for any decisions made based on divination results from this site. For professional advice, please consult qualified professionals in the relevant field.",
      },
      {
        heading: "3. User Conduct",
        body: "By using this service, you agree to:\n• Not abuse or maliciously use this service\n• Not attempt to damage, interfere with, or gain unauthorized access to our systems\n• Not use this service for any illegal purposes\n• Not impersonate others or misrepresent your affiliation with any person or entity",
      },
      {
        heading: "4. Intellectual Property",
        body: "The design, code, AI algorithms, content, and branding of this site are protected by intellectual property laws. No content may be copied, modified, distributed, or otherwise used without written permission.\n\nThe original I Ching text is part of the public domain cultural heritage. AI-generated interpretations are copyrighted by this site.",
      },
      {
        heading: "5. Service Changes",
        body: "We reserve the right to modify, suspend, or terminate the service at any time without prior notice. We may also update these terms from time to time. Continued use of the service constitutes acceptance of the updated terms.",
      },
      {
        heading: "6. Governing Law",
        body: "These terms are governed by the laws of the People's Republic of China. Any disputes arising from these terms shall be resolved through amicable negotiation; failing that, they shall be submitted to a court of competent jurisdiction.",
      },
    ],
  },
};

export default function TermsContent() {
  const locale = useLocale();
  const content = CONTENT[locale as keyof typeof CONTENT] || CONTENT.en;

  const navItems = useNavItems();

  return (
    <PageLayout navItems={navItems} maxWidth="max-w-6xl">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <span className="text-4xl mb-4 block">📋</span>
          <h1 className="text-3xl sm:text-4xl font-bold text-[var(--color-gold)] mb-3">
            {content.title}
          </h1>
          <p className="text-gray-500 text-sm">{content.lastUpdated}</p>
        </div>

        <div className="space-y-8">
          {content.sections.map((section, i) => (
            <section
              key={i}
              className="bg-[rgba(255,255,255,0.03)] border border-[rgba(201,169,110,0.12)] rounded-xl p-6"
            >
              <h2 className="text-lg font-bold text-[var(--color-gold)]/90 mb-3">
                {section.heading}
              </h2>
              <p className="text-gray-300 leading-relaxed whitespace-pre-line">
                {section.body}
              </p>
            </section>
          ))}
        </div>

        <div className="text-center mt-12">
          <Link
            href="/"
            className="inline-block px-8 py-3 rounded-full border border-[var(--color-gold)]/40 text-[var(--color-gold)] hover:bg-[var(--color-gold)]/10 transition-all duration-300"
          >
            {locale === "en" ? "Back to Home" : "返回首页"}
          </Link>
        </div>
      </div>
    </PageLayout>
  );
}
